config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get    '/sign_in',    to: 'sessions#sign_in_form'
  post   '/sign_in',    to: 'sessions#sign_in'
  delete '/sign_out',   to: 'sessions#sign_out'

  get    '/tweets',     to: 'tweets#index'
  get    '/tweets/new', to: 'tweets#new', as: 'new_tweet'
  post   '/tweets',     to: 'tweets#create'
  get    '/tweets/:id', to: 'tweets#show', as: 'tweet'
  get    '/tweets/:id/edit', to: 'tweets#edit', as: 'edit_tweet'
  patch  '/tweets/:id', to: 'tweets#update'
  delete '/tweets/:id', to: 'tweets#delete', as: 'delete_tweet'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :tweets
  # label: string
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :usertags
  before_save :update_tags
  before_save :update_usertags

  default_scope { where(deleted_at: nil) }
  scope :active, -> { where(deleted_at: nil) }
  scope :deleted, -> { where.not(deleted_at: nil) }

  def self.all_but_deleted
    Tweet.where(deleted_at: nil)
  end

  def update_tags
    self.tags = extract_hashtags
  end

  def update_usertags
    self.usertags = extract_usertags
  end

  private

  def extract_hashtags
    content.split(' ').filter do |word|
      word.start_with?('#')
    end.map do |hashtag|
      fetched = Tag.find_by(label: hashtag)
      fetched || Tag.create(label: hashtag)
    end
  end

  def find_user_by_mention(mention)
    username = mention.delete_prefix('@')
    mentionned_user = User.find_by(username: username)
    if mentionned_user
      fetched = Usertag.find_by(user_id: mentionned_user.id)
      return fetched || Usertag.create(user: mentionned_user)
    end
  end

  def extract_usertags
    content.split(' ').filter do |word|
      word.start_with?('@')
    end.map do |mention|
      find_user_by_mention(mention)
    end.filter do |user|
      user != nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # L’utilisateur doit pouvoir garder un mot de passe sécurisé.
  has_secure_password

  # L’email ne doit pas être nul, et doit être unique dans toute la base.
  validates :email, presence: true, uniqueness: true

  # L’utilisateur a plusieurs tweets avec une colonne user_id dans la table Tweets.
  has_many :tweets
end

app/models/usertag.rb
class Usertag < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :retrieve_current_user
  
  def retrieve_current_user
    if session[:user_token] != nil
      user = User.find_by(id: session[:user_token])
      @current_user = user
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def sign_in_form
  end

  def sign_in
    email = params[:login][:email]
    password = params[:login][:password]
    user = User.find_by(email: email)
    ret = user && user.authenticate(password)
    if ret
      session[:user_token] = user.id.to_s
      redirect_to users_path
    else
      redirect_to sign_in_path, notice: 'Wrong credentials'
    end
  end

  def sign_out
    session[:user_token] = nil
    redirect_to users_path
  end

  private

  def sessions_params
    params.require(:login).permit(:email, :password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authorize_user, only: [:new, :create, :edit, :update, :delete]
  before_action :set_tweet, only: [:edit, :update, :delete]
  before_action :redirect_user_if_no_tweet, only: [:edit, :update, :delete]

  def index
    @tweets = Tweet.all
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = @current_user
    if @tweet.save
      redirect_to tweets_path
    else
      redirect_to new_tweet_path, notice: 'Wrong'
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path
    else
      redirect_to edit_tweet_path(@tweet), notice: 'Wrong'
    end
  end

  def delete
    @tweet.update(deleted_at: Time.now)
    redirect_to tweets_path
  end

  private

  def set_tweet
    @tweet = Tweet.find_by(id: params[:id])
  end

  def authorize_user
    if @current_user.nil?
      redirect_to sign_in_path
    end
  end

  def redirect_user_if_no_tweet
    if @tweet.nil? || @current_user.id != @tweet.user.id
      redirect_to tweets_path
    end
  end

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :username
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      Bonjour
      <% if @current_user %>
        <%= @current_user.name %>
        <%= link_to "Sign out", '/sign_out', method: :delete %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= notice %>
<%= form_for @tweet do |f| %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<%= link_to "New tweet", new_tweet_path %>
<% for tweet in @tweets %>
  <div style="padding: 10px; border: 1px solid #ddd; margin: 10px; border-radius: 5px;">
    <div class="">
      Content
    </div>
    <div class="">
      <%= tweet.content %>
    </div>
    <div style="padding: 20px"></div>
    <div class="">
      Username
    </div>
    <div class="">
      <%= tweet.user.name %>
    </div>
    <div style="padding: 20px"></div>
    <div class="">
      Tags
    </div>
    <div class="">
      <% for tag in tweet.tags %>
        <%= tag.label %>
      <% end %>
    </div>
    <div style="padding: 20px"></div>
    <div class="">
      Mentions
    </div>
    <div class="">
      <% for usertag in tweet.usertags %>
        <%= usertag.user.username %>
      <% end %>
    </div>
    <%= link_to "Edit", edit_tweet_path(tweet) %>
    <% if tweet.user == @current_user %>
      <%= link_to "Delete", delete_tweet_path(tweet), method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/tweets/new.html.erb
<%= notice %>
<%= form_for @tweet do |f| %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/show.html.erb
<div style="padding: 10px; border: 1px solid #ddd; margin: 10px; border-radius: 5px;">
  <div class="">
    Content
  </div>
  <div class="">
    <%= @tweet.content %>
  </div>
  <div style="padding: 20px"></div>
  <div class="">
    Username
  </div>
  <div class="">
    <%= @tweet.user.name %>
  </div>
  <div style="padding: 20px"></div>
  <div class="">
    Tags
  </div>
  <div class="">
    <% for tag in @tweet.tags %>
      <%= tag.label %>
    <% end %>
  </div>
  <%= link_to "Edit", edit_tweet_path(@tweet) %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>